### ISSUE TITLE
Not able to import project from other git provider

### ISSUE THREAD

**Issue by yelhouti** [jenkins-x/jx-project#235]
The PR to change the dev environment when importing uses the scm client for the imported project, this is not always true.
https://github.com/jenkins-x/jx-project/blob/c6bb71a92eb60cf23fe7b1170274c907ca3ea068/pkg/cmd/importcmd/source_config_pr.go#L48-L63

The scm info should be retrieved from k8s sourceRepository instead.

To reproduce, create a project in gitlab for example, and try to import it in your dev git repository inside github (or the opposite)

**Comment by jstrachan** [comment]
I think this is fixed now; we've BDD tests passing for github, gitlab, github enterprise, bitbucket server and gitea
