### ISSUE TITLE
Jx3 unable to create repo on gitlab using go-scm

### ISSUE THREAD

**Issue by pow-devops2020** [jenkins-x/jx-project#48]
@jstrachan and the team of jx3 have finished migration of `jx promote` and `jx project` last week using `go-scm` for all git repository operations. But when I used the lasted jx-cli to run `jx project quickstart --git-user myusername --git-token mytoken --git-kind gitlab --pr-poll-timeout 30m0s`, it failed with this error message error: `failed to create git repository myusername/projectname: json: cannot unmarshal array into Go value of type gitlab.gl_namespace`. It seemed like it's not able to create repo on gitlab.

I also have encountered this error: `error: failed to validate options: failed to create ScmClient: failed to find git token: could not find git token for git server mygitlaburl` when I randomly tried `jx project spring --git-kind gitlab`.

What could be the cause of this behaviour?

I would be very grateful if anyone can take a look at this issue.

**Comment by yelhouti** [comment]
@pow-devops2020 I just made a PR that allowed me to jx import a project, https://github.com/jenkins-x/go-scm/pull/190 maybe once merged you can test again
