### ISSUE TITLE
fails if no git user/token found in $HOME/git/credentials

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx-project#75]
we get this error which is not very helpful:
```
error: failed to validate options: failed to create ScmClient: failed to find git token: could not find git token for git server https://github.com
```

we should prompt the user for a git user/token (or at least give better help).

## Workaround 

a workaround is either:

* supply ` --git-user myuser --git-token <bot_git_token>`

* populate git credentials by hand...

```bash
mkdir -p $HOME/git
echo https://myuser:mytoken@github.com >> $HOME/git/credentials
```

**Comment by salaboy** [comment]
@jstrachan this now has changed from `--git-user` to `--git-username`
